### ISSUE TITLE
6DOF rotation matrix deserialization type error 

### ISSUE THREAD

**Issue by tbolin** [qualisys/qualisys_cpp_sdk#7] opened 2020-01-31 14:06 UTC
https://github.com/qualisys/qualisys_cpp_sdk/blob/d5ab250c420ab14cd53f85c600b8d3554a9197d9/RTPacket.cpp#L842
The when deserializing the rotation matrix for 6DOF bodies the data is cast to a double pointer. However, the offset between values are only four bytes (i * 4). 

When testing with QTM 2.17 i got a correct rotation matrix if the cast was changed to float instead of double. 
There are enough data in the package for double precision, so I am not sure what is going on here.

**Comment by nilzilch** [comment] 2020-03-04 12:32
Version 1.7 and older versions of the protocol had a bug in the 6dof data sent from qtm. The data was sent as floats instead of doubles. There was also a bug in the sdk, when parsing the pre 1.8 6dof data. This is fixed in latest version of the sdk.

**Closed by nilzilch** 2020-03-04 12:32 UTC

**Comment by tbolin** [comment] 2020-03-11 13:23
Hi!
The latest version still de-serializes the rotation matrix incorrectly. 
At least for 1.7 the amount of data that is sent for each 6DOF body corresponds to the rotation matrix being sent as doubles. The data is however sent as floats. The second half of the data that is currently interpreted as a rotation matrix is just junk.
changing the line 
https://github.com/qualisys/qualisys_cpp_sdk/blob/a7fab1371b5e0d7c1d843032079c03c6821d9c44/RTPacket.cpp#L842
to
```afRotMatrix[i] = (float)SetByteOrder((float*)(pData + 40 + (i * 4) + nBodyIndex * 96))```
gives a correct rotation matrix.

**Comment by nilzilch** [comment] 2020-03-11 16:00
Are you using the latest version of QTM (v 2020.1)?
The bug you found was actually two bugs. One being in the sdk, in RTPacket.cpp. The other bug was in the rt server in QTM. The bug in QTM, was that version 1.7 and earlier of the protocol sent floats for the 6dof data instead of doubles. So you have to ave the latest QTM togeter with the latest cpp sdk.

Prior to protocol version 1.8, data was sent as doubles. But that was changed to floats in v 1.8.

**Comment by tbolin** [comment] 2020-03-11 17:39
I'm using QTM 2.17, so maybe this is an old bug from that version of QTM. 
However I have confirmed that requesting protocol version 1.7 from this QTM version gives rotation matrices that takes up space as they are given as doubles, but the data only makes sense if the first half of that data is interpreted as floats.

**Comment by nilzilch** [comment] 2020-03-12 08:05
Version 1.8 of the rt protocol was released with QTM 2.5 in 2011. It introduced the bug we are talking about. The bug in the server is that the rotation matrix is sent as floats, but the position of the 6dof is doubles (as intended). Also the sise of the packet is wrong. It is calculated as if it was doubles.
The cpp sdk was written some years after the server bug was introduced.
If you for some strange reason can not use a version later than 1.7 of the rt protocol, you have to use QTM 2020.1 or apply the fix your self locally.

**Comment by tbolin** [comment] 2020-03-12 09:13
Ok, I think I get it then. I guess the best fix on my end would be to use a newer version of the protocol. 
The reason I cared about the 1.7 version of the protocol is that the ROS mocap library from Kumar Robotics is hard coded to use it.
And thanks for directing me to the new version of the SDK. It's so much easier to work with.
